<a href="https://colab.research.google.com/github/markvasin/deep_learning_exercise/blob/master/lab1/Lab1_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
def sgd_factorise(A: torch.Tensor, rank: int, num_epochs=1000, lr=0.01):
  row, col = A.shape
  U = torch.rand(row, rank)
  V = torch.rand(col, rank)
  for epoch in range(0, num_epochs):
    for r in range(0, row):
      for c in range(0, col):
        e = A[r,c] - U[r,:] @ V[c,:].T
        U[r,:] = U[r,:] + (lr*e*V[c,:])
        V[c,:] = V[c,:] + (lr*e*U[r,:])
  return U,V


In [ ]:
A = torch.tensor([[0.3374, 0.6005, 0.1735], [3.3359, 0.0492, 1.8374], [2.9407, 0.5301, 2.2620]])
print(A)
U,V = sgd_factorise(A, 2, num_epochs=1000)
print(U)
print(V)
print(U @ V.T)
loss = torch.nn.functional.mse_loss(U@V.T, A, reduction='sum')
print(loss)
print('The reconstruction loss is', loss.item())

tensor([[0.3374, 0.6005, 0.1735],
        [3.3359, 0.0492, 1.8374],
        [2.9407, 0.5301, 2.2620]])
tensor([[-0.3199,  0.4377],
        [ 1.4785,  0.8221],
        [ 0.8738,  1.2249]])
tensor([[ 1.3669,  1.5015],
        [-0.4669,  0.8243],
        [ 0.6178,  1.2829]])
tensor([[ 0.2200,  0.5101,  0.3639],
        [ 3.2554, -0.0127,  1.9681],
        [ 3.0336,  0.6017,  2.1113]])
tensor(0.1221)
The reconstruction loss is 0.12208190560340881


In [ ]:
print(A)
U,S,V = torch.svd(A)
print(S)
S[-1] = 0
print(S)
# print(U)
# print(V)
print(U@torch.diag(S)@V.T)
loss = torch.nn.functional.mse_loss(U@torch.diag(S)@V.T, A, reduction='sum')
print(loss.item())

tensor([[0.3374, 0.6005, 0.1735],
        [3.3359, 0.0492, 1.8374],
        [2.9407, 0.5301, 2.2620]])
tensor([5.3339, 0.6959, 0.3492])
tensor([5.3339, 0.6959, 0.0000])
tensor([[ 0.2245,  0.5212,  0.3592],
        [ 3.2530, -0.0090,  1.9737],
        [ 3.0378,  0.5983,  2.1023]])
0.12191088497638702


In [ ]:
def sgd_factorise_masked(A: torch.Tensor, M: torch.Tensor, rank: int, num_epochs=1000, lr=0.01):
  row, col = A.shape
  U = torch.rand(row, rank)
  V = torch.rand(col, rank)
  for epoch in range(0, num_epochs):
    for r in range(0, row):
      for c in range(0, col):
        if M[r,c] == 1:
          e = A[r,c] - U[r,:] @ V[c,:].T
          U[r,:] = U[r,:] + (lr*e*V[c,:])
          V[c,:] = V[c,:] + (lr*e*U[r,:])
  return U,V

In [ ]:
M = torch.tensor([[1, 1, 1], [0, 1, 1], [1, 0, 1]])
U, V = sgd_factorise_masked(A, M, 2)
print(A)
print(U)
print(V)
loss = torch.nn.functional.mse_loss(U@V.T, A, reduction='sum')
print(loss)
print('Reconstructed matrix')
print(U @ V.T)

tensor([[0.3374, 0.6005, 0.1735],
        [3.3359, 0.0492, 1.8374],
        [2.9407, 0.5301, 2.2620]])
tensor([[ 0.5975, -0.4014],
        [ 0.9416,  1.1373],
        [ 1.2984,  1.2587]])
tensor([[ 1.2583,  1.0385],
        [ 0.6649, -0.5072],
        [ 0.8875,  0.8811]])
tensor(1.0341)
Reconstructed matrix
tensor([[0.3349, 0.6008, 0.1766],
        [2.3659, 0.0492, 1.8378],
        [2.9410, 0.2248, 2.2615]])
